// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.0 (Build Build 614 04/24/2018)
// Created on Thu Oct 12 21:46:00 2023

RAM RAM_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.address(address_sig) ,	// input [31:0] address_sig
	.data_write(data_write_sig) ,	// input [31:0] data_write_sig
	.write_en(write_en_sig) ,	// input  write_en_sig
	.read_en(read_en_sig) ,	// input  read_en_sig
	.data_out(data_out_sig) 	// output [31:0] data_out_sig
);

